### ISSUE TITLE
Hauptklasse der forge.jar konnte nicht gefunden werden

### ISSUE THREAD

**Issue by phecdaDia** [AtomSponge/hosencorp-2#1]
Guten Tag,  
wir wollten einen  kleinen Server auf Linux aufsetzen. Dabei kam jedoch immer der Fehler:  'Hauptklasse forge-1.7.10-10.13.4.1492-1.7.10-universal.jar konnte nicht gefunden oder geladen werden'. Es gibt leider keine weiteren Errorlogs, daher der Server nicht startet. Zudem haben wir versucht die mitgelieferte forge.jar mit einer anderen ( ebenfalls Mincecraft Version 1.7.10 ) zu ersetzen. Es kam jedoch der selbe Fehler :/

**Comment by Bandelenth** [comment]
Da ist ein Fehler im Startskript, anstatt

_java -Xmx4096M -XX:MaxPermSize=256M forge-1.7.10-10.13.4.1492-1.7.10-universal.jar nogui_

muss es heißen

_java -Xmx4096M -XX:MaxPermSize=256M **-jar** forge-1.7.10-10.13.4.1492-1.7.10-universal.jar nogui_

**Comment by phecdaDia** [comment]
Vielen Dank! Nun funktioniert alles :)
