### ISSUE TITLE
Rezepte für Flüßigkeiten

### ISSUE THREAD

**Issue by Avaborg** [AtomSponge/hosencorp-2#12]
Morschn,

wenn ich mir auf dem Hosisten-Server im NEI die Rezepte für Flüßigkeiten anzeigen lassen will, stürzt Minecraft ab. Im Singleplayer funktiont es aber ohne Probleme.

Crash-Log: http://pastebin.com/rfkVP6Be

Grüße,
Avaborg

**Comment by AtomSponge** [comment]
Gendustry wurde auf dem Server entfernt, da es in Verbindung mit Forestry abnormale Lags und einen Log von knapp 4GB in weitaus weniger als einer Stunde verursacht hat.
Wird voraussichtlich bei nächsten Update auch aus dem Modpack entfernt.
