### ISSUE TITLE
Installation hängt sich bei journeymap auf

### ISSUE THREAD

**Issue by DaDigga** [AtomSponge/hosencorp-2#13]
Heyhey,

nach Neuinstallation vom Tekkitlauncher wollte ich das Modpack erneut laden. Soweit lief auch alles richtig.
Beim herunterladen der Mods gibt es aber scheinbar ein Problem. Wenn der Mod Journeymap heruntergeladen wird, erscheint ein Popup, welches sagt: Failed to download [...]  Bitte sprich mit dem Macher des Packs.

Popup: http://www.directupload.net/file/d/4177/cokyw63j_jpg.htm
![fehleroutput](https://cloud.githubusercontent.com/assets/15930841/11281078/3414b86c-8ef9-11e5-828b-0d48cdc13ed9.jpg)

Liegt das nun an meiner eigenen Doofheit, oder ist da was kaputtgegangen?  :D 

Schönen Gruß

**Comment by Bandelenth** [comment]
Da scheint in der Tat etwas nicht zu funktionieren. Ich hab den Fehler bisher noch nicht gefunden, bin aber dran.

**Comment by Bandelenth** [comment]
Das Problem hängt mit dem Download von Journeymap zusammen, den wir aufgrund der Lizenzbestimmungen nicht selbst anbieten können. Die verwendete Version der Journey Map wird nicht mehr zum Download angeboten, mit der nächsten Version des Modpacks wird in irgendeiner Form das Problem behoben werden. Mehr steht zum bisherigen Zeitpunkt noch nicht fest. Leider können wir momentan das Problem leider nicht beheben.

**Comment by DaDigga** [comment]
Könnte es funktionieren, wenn ich mir die Modfiles besorge und in den angelegten Ordner vom Launcher einfüge? Der sucht ja nach bereits vorhandenen Files, er müsste die dann ja finden und weiter laden...

**Comment by Bandelenth** [comment]
Es könnte funktionieren, wäre einen Versuch wert. Ich wüsste allerdings grade nicht wie man an die Datei herankommen sollte ohne jemanden mit vorhandener Installation um die Datei zu fragen.

**Comment by DaDigga** [comment]
Das wäre kein Problem, ich werds übers Wochenende mal probieren und teile dann mit, wie es gelaufen ist.

**Comment by AtomSponge** [comment]
Der Download der JourneyMap Solder-Zip von CurseForge müsste wieder funktionieren, die Datei war temporär nicht verfügbar.
