### ISSUE TITLE
Serverproblem

### ISSUE THREAD

**Issue by DaDigga** [AtomSponge/hosencorp-2#14]
Hey, ich bins nochmal...

Läuft nun alles wieder soweit rund, aber: 

Ich spiele auf einem Server, gehostet bei Nitrado, welcher zu anfang nicht erreichbar war.
Nachdem wiir dann öfter mal neugestartet haben, fiel die Fehlermeldung: 

java.lang.IllegalArgumentException: Duplicate enchantment id! class flaxbeard.thaumicexploration.enchantment.EnchantmentNightVision and class mariculture.magic.enchantments.EnchantmentFlight Enchantment ID:78
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
    at flaxbeard.thaumicexploration.enchantment.EnchantmentNightVision.<init>(EnchantmentNightVision.java:16)
    at flaxbeard.thaumicexploration.ThaumicExploration.load(ThaumicExploration.java:501)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

auf. Diese haben wir versucht selber zu beseitigen indem wir die ID´s in 90,92,91 geändert haben. Nachdem der Konflikt mit den ID`s beseitigt war, startet der Server wieder soweit, dass man über den Launcher joinen könnte. Im Log vom Server sagt Forge, dass "missing Blocks and Items" vorhanden sind, dadurch bricht die Verbindung zum Server auf mit der Fehlermeldung "Fatally missing Blocks and Items" ab.

Auszug aus der Konsole:

[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:focusXPDrain
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothChestGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:protoclay
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorSwordGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:placementMirror
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothHelm
 [B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorShovel
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:warpGate
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorSword
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:focusShadowbeam
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothHelmGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorPickGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorAxe
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:skyPearl
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothBoots
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothChest
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorPick
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothLegsGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:catAmulet
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:kamiResource
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorPouch
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorShovelGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:focusRecall
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorAxeGem
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothLegs
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:blockTalisman
[B#328]  [20:20:32] [Netty Client IO #1/INFO] [FML]: Found a missing id from the world ThaumicTinkerer:ichorclothBootsGem

Eigentlich ist nichts verändert worden, bloß auf einmal will der Server nicht mehr so, wie vorher. Gabs ein internes Update? Gibts irgendwelche Lösungsvorschläge?

Gruß

**Comment by AtomSponge** [comment]
Bitte kompletten Forge-Log via [GitHub Gist](https://gist.github.com/) oder [Pastebin](http://pastebin.com/) posten.

**Comment by DaDigga** [comment]
https://gist.github.com/DaDigga/1a799403b8eeb1e452f3   

Ich hoffe das ist der richtige Log.

**Comment by AtomSponge** [comment]
@DaDigga Entschuldige die späte Antwort, wir haben die Issue total vergessen... Falls das Problem noch immer besteht: Sieht so aus, als ob Nitrado irgendwelche Dateien gelöscht/verändert hat. Gab es eventuell ein Problem mit der Festplatte? Der Log im Gist ist auch nicht vollständig, und Mods sollten eigentlich nicht plötzlich verschwinden.

**Comment by AtomSponge** [comment]
Ich nehme an, das Problem wurde inzwischen gelöst :smirk:
