### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by MaximalesGaming** [AtomSponge/hosencorp-2#16]
Lieber Schwamm/AtomSponge,
ich und meine Freund möchten das Hosencorp 2 Modpack auf einen Server spielen. Habe ich irgend etwas zu beachten (spezielle Dateien für den Serverbetrieb) oder kann ich einfach die Mods in den Server-Modordner kopieren??

Danke im vorraus.

LG MaximalesGaming

**Comment by Bandelenth** [comment]
Hallo MaximalesGaming,

Auf der Modpack-Seite des Hosencorp 2 Modpacks findet sich der Downloadlink für den fertig gebauten Server. (http://www.technicpack.net/modpack/hosencorp-2.732466)
_Streng genommen ist das hier eigentlich ein Bugtracker und damit eigentlich nicht für Fragen zuständig, die man durch einfaches Googlen herausbekommen kann ;-)_

Bandelenth
