### ISSUE TITLE
Auto-chisel

### ISSUE THREAD

**Issue by Thoughtless1984** [AtomSponge/hosencorp-2#2]
Der Target Slot des auto-chisel von Chisel2 ist defekt, man kann keine Blöcke reinpacken. Ist wohl ein Problem vom Mod, aber noch keine offizielle Lösung vorhanden.

**Comment by AtomSponge** [comment]
In Version 1.2.0 behoben ([Changelog](http://www.technicpack.net/modpack/hosencorp-2.732466/changelog/232841))
