### ISSUE TITLE
Hosencorp 2 Server wird als Vanilla-Server erstellt

### ISSUE THREAD

**Issue by ghost** [AtomSponge/hosencorp-2#21]
Hallo Schwamm.
Ich habe versucht einen privaten Hosencorp-Server auf meinem PC zu erstellen. Dazu habe ich die offizielle Serverdatei mit der Version 1.2.0 verwendet. Der Server ist zwar erstellt worden und es ist auch möglich zu joinen aber es wird nur ein Vanilla-Server erstellt. Ich habe mal die log-Datei und die fml-server-latest angehängt, falls du mehr benötigst schreib einfach. Danke für die Hilfe schon einmal im Voraus.

2FAST4YOU

[fml-server-latest.txt](https://github.com/AtomSponge/hosencorp-2/files/264651/fml-server-latest.txt)
[2016-05-14-5 log.txt](https://github.com/AtomSponge/hosencorp-2/files/264646/2016-05-14-5.log.txt)

**Comment by AtomSponge** [comment]
Lad' das Serverarchiv mal erneut herunter, entpacke es, und starte die Forge-Jar (start.bat/start.sh tun dies auch).
Der Forge Server ist beim Start gecrashed - warum auch immer, Crashlog wäre hilfreich - und danach hast du anscheinend die minecraft_server.1.7.10.jar anstatt der Forge-Jar gestartet.

**Comment by ghost** [comment]
Ok. Habe es jetzt neu heruntergeladen entpackt und die Forge-Jar gestartet. Dann die EULA akzeptiert und die IP eingestellt. Jetzt läuft es ok, bzw waren noch keine Probleme. War wahrscheinlich mein Fehler, da ich die minecraft_server.1.7.10.jar statt der Forge gestartet habe^^.
