### ISSUE TITLE
Das Pack bitte updaten

### ISSUE THREAD

**Issue by Nico1976** [AtomSponge/hosencorp-2#22]
Könnte man dies Paket komplett updaten damit zb Ender IO maschienen, und einige bugs behoben werden da bei uns, doch noch recht viele user spielen

auch könnte man ja noch den ein oder anderen mod hinzufügen um etwas mehr komfor zu haben 

mfg nico1976

**Comment by Bandelenth** [comment]
Ein Update der Mods kommt sobald bei uns Zeit dafür ist, das ist völlig klar, ich kann allerdings nicht sagen wann das das nächste Mal sein wird, Zeit ist eine rare Ressource. Darüber hinaus Mods hinzuzufügen oder zu ändern passiert ausschließlich auf Wunsch der Serienteilnehmer, da das Modpack hierfür entwickelt wurde, dafür bitte ich um Verständnis.

**Comment by Nico1976** [comment]
nagut dann muss man damit leben zwecks neuer mods

aber haben wir zb weiterhin das problem mit den auto chisel das er nicht geht, oder das zb von ender io die crafter einfach despawn wenn man was mit ihn macht, usw usw

und das euren Ressourcen an bearbeiten der mods knapp ist mir klar, aber war ja nur ein Wunsch, den manchmal sind die mod Packs zwecks aktualisieren quasi aufs abgestellt Kleis verschoben ;)

mfg nico1976

**Comment by AtomSponge** [comment]
Dann solltet ihr diese Mods, falls bisher nicht geschehen, mit genauer Fehlerbeschreibung melden, das hilft uns mehr als wenn ständig jemand fragt, wann das Modpack geupdated wird. Wie @Bandelenth bereits erwähnte, wenn wir genügend Zeit dazu haben, du musst bedenken, dass wir das alles in unserer Freizeit machen.
