### ISSUE TITLE
Modpack Download

### ISSUE THREAD

**Issue by Drago100ful** [AtomSponge/hosencorp-2#25]
A mod is missing on the download server. So it won't download properly and just stop with an error message that JourneyMap is missing/can't be downloaded from xdqmhose's server.

The mod missing/corrupted is:
JourneyMap

**Comment by Bandelenth** [comment]
It may be that the mod was temporarily unavailable, it is not distributed by us but instead just referenced, because the license terms require us to do so. My sincere apollogies for the inconvenience, I was able to start the download just now.

**Comment by AtomSponge** [comment]
See #27 for more information.
