### ISSUE TITLE
Modpack Download

### ISSUE THREAD

**Issue by Drago100ful** [AtomSponge/hosencorp-2#27]
Still it isn't working properly. Why do you close a thread/issue when it's not fixed?
![erorr](https://cloud.githubusercontent.com/assets/20770456/17328532/81dea47e-58be-11e6-8afa-059da8b87037.PNG)

**Comment by Bandelenth** [comment]
There is nothing really that we could do about it. The file is downloadable, I can confirm that and is not hosted on our infrastructure. The URL returns a redirect.

**Comment by Drago100ful** [comment]
I know that it's downloadable, but the TechnicLauncher doesn't allow skips or manual insertion of the mod. Still thanks that you tried to help. You may want this issue marked as done or reply to the issue when it's fixed.

**Comment by KhorneHoly** [comment]
Sadly, there's still the same issue going on. I can't download the modpack. Is there any solution to solve this manually?

![download_error](https://cloud.githubusercontent.com/assets/3071746/19015917/d9b2b0f4-880d-11e6-8e79-45938846a002.JPG)

**Comment by AtomSponge** [comment]
@KhorneHoly I just posted a new update without JourneyMap, so the download issues should be resolved. 

Excerpt from the changelog entry: 

> We are not allowed to redistribute JourneyMap, so we're redirecting requests via Solder to CurseForge - either the launcher doesn't like that or CurseForge has/had outages.
> You can still manually download JourneyMap from https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716 and move it to the mod directory (%userprofile%\.technic\modpacks\hosencorp-2\mods on Windows or ~/.technic/modpacks/hosencorp-2/mods on Linux, may differ depending on your launcher settings).

**Comment by KhorneHoly** [comment]
Now it does work, thanks!
