### ISSUE TITLE
Update Pls

### ISSUE THREAD

**Issue by ImS1mple** [AtomSponge/hosencorp-2#28]
Hmmm...wollte mal fragen ob du ein paar mods hinzufügen könntest unswar...Optifine, Dinosaurier mod und vlt. ein paar Fans mod Update packs (mit mehr waffen wie Stand MG42 oder mehr Flans mod Autos)!
und bitte ein Server Update machen mit oder ohne den mods :)
LG Jan

**Comment by Bandelenth** [comment]
Ursprünglich wurde das Modpack, wie dir sicherlich bekannt ist, für die Serie Hosencorp vs. Mighty Pirates erstellt. Wir spielen schon eine ganze Weile nicht mehr mit dem Pack und werden daher leider auch keine Zeit haben an diesem etwas zu verändern.
Natürlich freuen wir uns, dass das Pack nach wie vor gespielt wird, von daher hier ein paar Tipps wie du vielleicht dem gewünschten Ergebnis etwas näher kommen kannst:
- Optifine ist meines Wissens nach ein reiner client-side Mod, den müsstest du über den Launcher einfach hinzufügen können.
- Was die Flans-Mod Packs angeht, bin ich der Meinung, dass man die auch vergleichsweise einfach ergänzen kann ohne etwas kaputt zu machen, aber da geht probieren wie immer über studieren... Hier hilft es definitiv die Flans Dokumentation mal zu lesen.

Ich hoffe dir ist damit ein wenig geholfen, ich werde den Issue auf jeden Fall hiermit auch schließen, da, wie bereits oben geschildert, von unserer Seite keine Arbeit mehr in dieses Modpack fließen wird. Falls Probleme mit den Hinweisen auftreten sollten, bitte ich dich Google zu befragen, da wir für Erweiterungen des Modpacks keinerlei Support übernehmen können.
