### ISSUE TITLE
Minecraft absturz nach update

### ISSUE THREAD

**Issue by Zeje1** [AtomSponge/hosencorp-2#3]
Wollte nur mal sagen, dass die 1.1.0 und die 1.1.1 nicht vernünftig laufen... 1.0.0 laufen ohne Probleme bei mir.. jedoch nach dem Update des Webservers und im TechnicLauncher schmiert immer Minecraft ab.

Spiele momentan wieder auf der 1.0.0 und da läuft es ...

Liebe Grüße Zeje

**Comment by AtomSponge** [comment]
Bitte Logs und - sofern vorhanden - Crashlogs nachreichen, sonst kann ich daran leider nicht viel tun.

**Comment by AtomSponge** [comment]
Aufgrund der Inaktivität seitens des Ticket-Autors nehmen wir an, dass der Fehler selbstständig behoben wurde.
