### ISSUE TITLE
Creosote Oil

### ISSUE THREAD

**Issue by Mattzi** [AtomSponge/hosencorp-2#4]
Die Rails kann man nicht craften da aus beiden coke ovens das IM Oil rauskommt und die schienen kein oredict nutzen

**Comment by AtomSponge** [comment]
Die Wooden Ties kann man via Craftingrezept sowohl mit dem Immersive Engineering, als auch mit dem Railcraft-Öl herstellen. Das Carpenterrezept kann ich so einfach leider nicht abändern.
