### ISSUE TITLE
Bekomme den Server nicht zum laufen - FML

### ISSUE THREAD

**Issue by DLZion** [AtomSponge/hosencorp-2#5]
Irgendwas scheint da nicht zu passen. Auf dem Server läuft Ubuntu und ein Vanilla Server. Ist das erste mal, das ich versuche einen Modserver zu starten... also wenns Unsinn ist, bitte einfach rauswerfen ^^'

Log: https://gist.github.com/anonymous/0b78281d484705acf64d

**Comment by Bandelenth** [comment]
"Java is OpenJDK 64-Bit Server VM, version 1.6.0_34, running on Linux:amd64:3.13.0-48-generic, installed at /usr/lib/jvm/java-6-openjdk-amd64/jre"
Da liegt das Problem. Java Version 6 (1.6) ist definitiv zu alt, bitte benutzt Java 8 (1.8). Ansonsten würde ich mir über das OpenJDK mal Gedanken machen, das Oracle Java ist performanter, aber closed source.
