### ISSUE TITLE
Java 1.7 benutzen

### ISSUE THREAD

**Issue by Skillersharkoon** [AtomSponge/hosencorp-2#6]
Hallo Schwamm, habe mal ne Frage bezüglich Java, denn ich ich möchte das Modpack gerne starten, doch ich benötige Java 1.8. Gibt es einen weg, indem ich das Modpack auch mit Java 17 starten kann? Denn Java 1.8 weißt auf viele Probleme hin, die ich gerne vermeiden möchte ;) 
MFG Skiller

**Comment by Bandelenth** [comment]
Was für Probleme gibt Java 1.7 denn aus? Man kann ja auch beide Versionen parallel betreiben, muss dann halt die executable angeben.

**Comment by Skillersharkoon** [comment]
Es wird gesagt, das ich Java 1.8 benutzen soll und ich haben mich jetzt dazu entschieden wieder ganz auf Java 1.8 umzusteigen ;)

**Comment by AtomSponge** [comment]
> Denn Java 1.8 weißt auf viele Probleme hin, die ich gerne vermeiden möchte ;) 

Die wären? Java 7 wird nicht mehr unterstützt, wie Bandelenth schon angemerkt hat, Java 8 nutzen.
