### ISSUE TITLE
Crash Version 1.1.1

### ISSUE THREAD

**Issue by RononDex6** [AtomSponge/hosencorp-2#7]
Moin Moin,
Ich versuche euer Modpack auf meinen Server zu installieren.
Soweit so gut nur bekomme ich nach dem Starten immer Folgende Fehlermeldung : 

Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
(http://pastebin.com/TVdcmREL  = Ganze Fehlermeldung )

Könntest du mir bitte helfen ?

MfG Felix aka Ronon

**Comment by AtomSponge** [comment]
Ports unter 1024 sind pri­vi­le­giert, du kannst sie also nicht ohne Weiteres als normaler Nutzer binden. Versuch es mal mit einem anderen Port, der über 1024 liegt.
Außerdem würde ich dir empfehlen, auf Java 8 zu updaten.

**Comment by RononDex6** [comment]
Ok danke ich probier es mal :D

**Comment by RononDex6** [comment]
Danke danke danke, er läuft jetzt :D 
Ich und meine M8's sind dir mega dankbar das du so schnell geantwortet hast.
Ich wünsch dir noch ein Abend.
