### ISSUE TITLE
Einsatz von Bukkit Plugins mittels Cauldron

### ISSUE THREAD

**Issue by DeadPlayed** [AtomSponge/hosencorp-2#8]
hallo

ist es möglich den server auch mit plugins zu nutzen z.b.: mit cauldron alias: mcpc plus ?
und wen ja. WIE?
Hab es versucht doch es wolte einfach nicht klappen. 
Bei eurem altenserver hatte ich es sehr schnell geschaft.

mfg.: Deadplayed und siggi

ps.: schönes mod pack aber, wenn man nur zu zweit spielt ZU VIELE ÜBERPAUERTE MOB´s.

**Comment by Bandelenth** [comment]
Ich gehe davon aus, dass es pauschal möglich ist, wir haben es aber weder getestet noch werden wir es offiziell unterstützen, weil es eine große potentielle Fehlerquelle ist und damit eine möglichst gute Spielerfahrung völlig außerhalb unseres Einflusses ist.

tl;dr Macht es wenn ihr wollt, es sollte möglich sein, aber modifizierte Installationen erhalten von uns keinen Support. Das Modpack ist grundsätzlich als provided as-is anzusehen.
