### ISSUE TITLE
Hosencorp 2 stürzt beim Hochfahren ab. 64bit Debian server. 

### ISSUE THREAD

**Issue by Dabako** [AtomSponge/hosencorp-2#9]

**Comment by AtomSponge** [comment]
Bitte überprüfe, ob der Minecraftserver [write Permissions](https://en.wikipedia.org/wiki/File_system_permissions) (rekursiv) für das gesamte Verzeichnis hat.

**Comment by Dabako** [comment]
Ja die Permissions waren tasächlich das Problem. Leichtsinnsfehler...

Danke (:
